env:
  env_name: RodentRun
  batch_size: 2_048
  
# collector
collector:
  frames_per_batch: 16_384
  total_frames: 67_108_864

# logger
logger:
  backend: wandb
  project_name: Test-Custom-TorchRL-Env
  exp_name: ppotest
  test_interval: 1_048_576
  num_test_episodes: 32

# Optim
optim:
  lr: 3e-4
  weight_decay: 0.0
  anneal_lr: True

# loss
loss:
  gamma: 0.99
  mini_batch_size: 512
  ppo_epochs: 10
  gae_lambda: 0.95
  clip_epsilon: 0.2
  anneal_clip_epsilon: False
  critic_coef: 0.25
  entropy_coef: 0.0
  loss_critic_type: l2